export const ACTION_TYPES = {
    LOGIN_LOADING: "LOGIN_LOADING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    
    
    LOGOUT: "LOGOUT",
    
    PRODUCTS_LOADING: "PRODUCTS_LOADING",
    PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
    PRODUCTS_FAIL: "PRODUCTS_FAIL",
};